#ifndef PLATFORM_SIGNALS_H
#define PLATFORM_SIGNALS_H

typedef enum {
	SIGNAL_REFERENCE_SPEED = 0,
	SIGNAL_REQUESTED_BRAKE,
	SIGNAL_FRONT_LEFT_GRIP_LOSS,
	SIGNAL_FRONT_RIGHT_GRIP_LOSS,
	SIGNAL_FRONT_LEFT_WHEEL_SPEED,
	SIGNAL_FRONT_RIGHT_WHEEL_SPEED,

	SIGNAL_FRONT_LEFT_WHEEL_SLIP,
	SIGNAL_FRONT_RIGHT_WHEEL_SLIP,
	SIGNAL_FRONT_LEFT_MOTOR_COMMAND,
	SIGNAL_FRONT_RIGHT_MOTOR_COMMAND,
	SIGNAL_FRONT_LEFT_SLIP_ACTIVE,
	SIGNAL_FRONT_RIGHT_SLIP_ACTIVE,

	SIGNAL_COUNT
} SignalId;

#endif
