/*
 * i2c_bus.c
 *
 * Layer 1 implementation. Thin wrapper over the STM32 HAL I2C driver.
 *
 * If you ever move the OLED to a different I2C instance, this file and the
 * .ioc are the only two places that need to change.
 */

#include "i2c_bus.h"
#include "main.h"          /* brings in the CubeMX handle declarations */

/* Generated by CubeMX in main.c when I2C2 is enabled for the Application
 * runtime context. */
extern I2C_HandleTypeDef hi2c2;

static I2C_HandleTypeDef *i2c_bus_handle = NULL;

void I2cBus_Initialize(void)
{
    i2c_bus_handle = &hi2c2;
}

bool I2cBus_WriteBytes(uint8_t device_address_8bit,
                       const uint8_t *data_bytes,
                       uint16_t byte_count,
                       uint32_t timeout_milliseconds)
{
    HAL_StatusTypeDef transfer_status;

    if ((i2c_bus_handle == NULL) || (data_bytes == NULL) || (byte_count == 0U))
    {
        return false;
    }

    transfer_status = HAL_I2C_Master_Transmit(i2c_bus_handle,
                                              (uint16_t)device_address_8bit,
                                              (uint8_t *)data_bytes,
                                              byte_count,
                                              timeout_milliseconds);

    return (transfer_status == HAL_OK);
}

bool I2cBus_IsDevicePresent(uint8_t device_address_8bit)
{
    if (i2c_bus_handle == NULL)
    {
        return false;
    }

    return (HAL_I2C_IsDeviceReady(i2c_bus_handle,
                                  (uint16_t)device_address_8bit,
                                  3U,                                      /* trials  */
                                  I2C_BUS_DEFAULT_TIMEOUT_MILLISECONDS) == HAL_OK);
}
